
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int colgroupOpen = 19;
  public static final int thClose = 34;
  public static final int thOpen = 33;
  public static final int htmlOpen = 4;
  public static final int bOpen = 72;
  public static final int basefontClose = 15;
  public static final int h4Close = 66;
  public static final int supOpen = 53;
  public static final int centerOpen = 57;
  public static final int dirClose = 38;
  public static final int h3Open = 63;
  public static final int trOpen = 29;
  public static final int RPAREN = 3;
  public static final int frameOpen = 77;
  public static final int LPAREN = 2;
  public static final int smallClose = 52;
  public static final int h5Close = 68;
  public static final int bodyClose = 9;
  public static final int aOpen = 35;
  public static final int optionClose = 26;
  public static final int bodyOpen = 8;
  public static final int tbody = 86;
  public static final int h2Open = 61;
  public static final int headOpen = 73;
  public static final int captionOpen = 75;
  public static final int tdClose = 32;
  public static final int thead = 81;
  public static final int fieldsetClose = 79;
  public static final int noframesClose = 13;
  public static final int h6Close = 70;
  public static final int captionClose = 76;
  public static final int img = 84;
  public static final int fieldsetOpen = 78;
  public static final int selectClose = 24;
  public static final int pOpen = 45;
  public static final int ulOpen = 39;
  public static final int tableOpen = 27;
  public static final int br = 83;
  public static final int centerClose = 58;
  public static final int smallOpen = 51;
  public static final int hr = 82;
  public static final int ulClose = 40;
  public static final int uOpen = 49;
  public static final int tableClose = 28;
  public static final int olClose = 44;
  public static final int basefontOpen = 14;
  public static final int olOpen = 43;
  public static final int subClose = 56;
  public static final int fontClose = 60;
  public static final int h1Open = 6;
  public static final int liClose = 42;
  public static final int formOpen = 21;
  public static final int trClose = 30;
  public static final int h6Open = 69;
  public static final int fontOpen = 59;
  public static final int aClose = 36;
  public static final int liOpen = 41;
  public static final int EOF = 0;
  public static final int h1Close = 7;
  public static final int dirOpen = 37;
  public static final int selectOpen = 23;
  public static final int endTag = 80;
  public static final int headClose = 74;
  public static final int supClose = 54;
  public static final int htmlClose = 5;
  public static final int error = 1;
  public static final int optionOpen = 25;
  public static final int uClose = 50;
  public static final int iOpen = 47;
  public static final int subOpen = 55;
  public static final int bClose = 71;
  public static final int h2Close = 62;
  public static final int h5Open = 67;
  public static final int divClose = 18;
  public static final int framesetOpen = 10;
  public static final int formClose = 22;
  public static final int tdOpen = 31;
  public static final int iClose = 48;
  public static final int divOpen = 17;
  public static final int dirOpendirClose = 16;
  public static final int colgroupClose = 20;
  public static final int h3Close = 64;
  public static final int input = 85;
  public static final int framesetClose = 11;
  public static final int pClose = 46;
  public static final int h4Open = 65;
  public static final int noframesOpen = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "htmlOpen",
  "htmlClose",
  "h1Open",
  "h1Close",
  "bodyOpen",
  "bodyClose",
  "framesetOpen",
  "framesetClose",
  "noframesOpen",
  "noframesClose",
  "basefontOpen",
  "basefontClose",
  "dirOpendirClose",
  "divOpen",
  "divClose",
  "colgroupOpen",
  "colgroupClose",
  "formOpen",
  "formClose",
  "selectOpen",
  "selectClose",
  "optionOpen",
  "optionClose",
  "tableOpen",
  "tableClose",
  "trOpen",
  "trClose",
  "tdOpen",
  "tdClose",
  "thOpen",
  "thClose",
  "aOpen",
  "aClose",
  "dirOpen",
  "dirClose",
  "ulOpen",
  "ulClose",
  "liOpen",
  "liClose",
  "olOpen",
  "olClose",
  "pOpen",
  "pClose",
  "iOpen",
  "iClose",
  "uOpen",
  "uClose",
  "smallOpen",
  "smallClose",
  "supOpen",
  "supClose",
  "subOpen",
  "subClose",
  "centerOpen",
  "centerClose",
  "fontOpen",
  "fontClose",
  "h2Open",
  "h2Close",
  "h3Open",
  "h3Close",
  "h4Open",
  "h4Close",
  "h5Open",
  "h5Close",
  "h6Open",
  "h6Close",
  "bClose",
  "bOpen",
  "headOpen",
  "headClose",
  "captionOpen",
  "captionClose",
  "frameOpen",
  "fieldsetOpen",
  "fieldsetClose",
  "endTag",
  "thead",
  "hr",
  "br",
  "img",
  "input",
  "tbody"
  };
}

