/* The following code was generated by JFlex 1.3.5 on 11/2/20, 8:25 PM */

    
import java_cup.runtime.Symbol;
    

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 11/2/20, 8:25 PM from the specification file
 * <tt>file:/C:/Users/Victor/eclipse-workspace/LexerHTML/lexer.jflex</tt>
 */
class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\41\0\1\0\10\0\1\0\2\0\1\2\1\0\1\10\1\0\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\5\0\1\1\1\36\1\3\42\0"+
    "\1\13\1\4\1\25\1\6\1\15\1\11\1\27\1\26\1\21\1\0"+
    "\1\37\1\24\1\14\1\20\1\5\1\22\1\0\1\12\1\16\1\17"+
    "\1\23\1\41\1\40\1\42\1\7\1\43\uff85\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    36,    72,   108,   144,   180,   216,   252,   288,   324, 
      360,   396,   432,   468,   504,   540,   576,   612,   648,   684, 
      720,   756,   792,   828,   864,    72,   900,   936,   972,  1008, 
       72,  1044,  1080,  1116,  1152,  1188,  1224,  1260,  1296,  1332, 
     1368,  1404,  1440,  1476,  1512,  1548,  1584,  1620,  1656,  1692, 
     1728,  1764,  1800,  1836,  1872,  1908,  1944,  1980,  2016,  2052, 
     2088,  2124,  2160,  2196,  2232,  2268,  2304,  2340,  2376,  2412, 
     2448,  2484,  2520,  2556,  2592,  2628,  2664,  2700,  2736,  2772, 
     2808,  2844,  2880,  2916,  2952,  2988,  3024,    72,  3060,    72, 
     3096,  3132,  3168,  3204,  3240,  3276,  3312,  3348,  3384,  3420, 
     3456,  3492,  3528,  3564,  3600,  3636,  3672,  3708,  3744,    72, 
       72,  3780,  3816,  3852,  3888,  3924,    72,    72,  3960,    72, 
     3996,    72,    72,    72,    72,    72,    72,  4032,  4068,  4104, 
     4140,  4176,  4212,  4248,  4284,  4320,  4356,  4392,  4428,  4464, 
     4500,  4536,  4572,  4608,  4644,  4680,  4716,  4752,  4788,  4824, 
     4860,  4896,  4932,  4968,  5004,  5040,  5076,  5112,  5148,  5184, 
     5220,  5256,  5292,  5328,  5364,  5400,  5436,  5472,  5508,  5544, 
     5580,  5616,  5652,  5688,  5724,  5760,  5796,  5832,  5868,  5904, 
     5940,    72,  5976,  6012,  6048,  6084,  6120,  6156,  6192,  6228, 
     6264,  6300,  6336,  6372,  6408,  6444,  6480,  6516,  6552,  6588, 
     6624,  6660,  6696,  6732,  6768,  6804,  6840,  6876,  6912,    72, 
     6948,  6984,  7020,  7056,  7092,    72,  7128,  7164,  7200,  7236, 
     7272,  7308,  7344,  7380,    72,    72,    72,  7416,  7452,  7488, 
     7524,  7560,  7596,  7632,  7668,  7704,  7740,  7776,  7812,  7848, 
     7884,  7920,    72,    72,  7956,  7992,  8028,  8064,    72,  8100, 
     8136,  8172,  8208,  8244,  8280,  8316,  8352,  8388,  8424,  8460, 
     8496,  8532,  8568,  8604,  8640,  8676,  8712,  8748,  8784,  8820, 
       72,  8856,  8892,  8928,  8964,    72,    72,  9000,  9036,    72, 
     9072,  9108,  9144,  9180,  9216,  9252,  9288,  9324,  9360,    72, 
     9396,  9432,  9468,  9504,  9540,  9576,  9612,  9648,  9684,  9720, 
     9756,  9792,  9828,  9864,  9900,  9936,  9972, 10008, 10044, 10080, 
    10116, 10152, 10188, 10224, 10260, 10296, 10332, 10368, 10404, 10440, 
    10476, 10512, 10548, 10584, 10620, 10656, 10692, 10728, 10764, 10800, 
    10836, 10872, 10908, 10944, 10980,    72, 11016, 11052, 11088,    72, 
    11124, 11160, 11196, 11232, 11268, 11304, 11340,    72,    72, 11376, 
       72, 11412,    72,    72, 11448, 11484,    72,    72,    72,    72, 
       72,    72,    72,    72, 11520, 11556, 11592, 11628, 11664, 11700, 
    11736, 11772, 11808,    72, 11844, 11880, 11916, 11952, 11988, 12024, 
    12060, 12096, 12132, 12168, 12204, 12240, 12276, 12312, 12348, 12384, 
    12420, 12456, 12492, 12528,    72, 12564,    72, 12600,    72, 12636, 
    12672, 12708, 12744, 12780,    72, 12816, 12852, 12888, 12924, 12960, 
    12996, 13032,    72, 13068, 13104, 13140, 13176, 13212,    72, 13248, 
    13284,    72, 13320, 13356, 13392, 13428,    72,    72, 13464,    72, 
    13500, 13536, 13572,    72, 13608,    72, 13644, 13680, 13716, 13752, 
    13788,    72, 13824, 13860, 13896, 13932, 13968, 14004,    72, 14040, 
       72, 14076, 14112, 14148, 14184, 14220, 14256, 14292, 14328, 14364, 
    14400, 14436, 14472, 14508, 14544, 14580, 14616,    72,    72, 14652, 
    14688, 14724, 14760, 14796,    72, 14832,    72,    72,    72, 14868, 
       72, 14904, 14940, 14976, 15012, 15048, 15084, 15120, 15156, 15192, 
    15228, 15264, 15300, 15336, 15372, 15408, 15444, 15480, 15516, 15552, 
    15588, 15624, 15660, 15696,    72, 15732,    72,    72,    72, 15768, 
    15804, 15840, 15876, 15912, 15948, 15984, 16020,    72,    72, 16056, 
       72, 16092,    72, 16128, 16164, 16200,    72, 16236, 16272,    72, 
    16308, 16344, 16380,    72, 16416, 16452, 16488, 16524,    72, 16560, 
    16596, 16632,    72,    72, 16668, 16704, 16740, 16776, 16812, 16848, 
       72, 16884,    72, 16920,    72,    72,    72, 16956,    72,    72, 
    16992, 17028, 17064, 17100, 17136, 17172,    72, 17208,    72, 17244, 
       72, 17280,    72, 17316, 17352, 17388,    72, 17424, 17460, 17496, 
    17532, 17568, 17604, 17640, 17676,    72, 17712, 17748, 17784, 17820, 
    17856,    72, 17892, 17928, 17964,    72, 18000, 18036, 18072, 18108, 
       72, 18144, 18180, 18216, 18252, 18288, 18324, 18360,    72, 18396, 
       72,    72, 18432,    72, 18468,    72,    72, 18504, 18540, 18576, 
    18612, 18648, 18684, 18720, 18756,    72,    72,    72,    72, 18792, 
    18828,    72, 18864,    72, 18900, 18936, 18972, 19008, 19044, 19080, 
    19116,    72, 19152,    72,    72,    72, 19188, 19224, 19260, 19296, 
       72, 19332, 19368,    72, 19404, 19440, 19476,    72,    72, 19512, 
       72, 19548, 19584, 19620, 19656,    72,    72,    72,    72, 19692, 
    19728, 19764,    72, 19800, 19836,    72,    72, 19872, 19908,    72, 
       72, 19944,    72,    72, 19980,    72, 20016,    72,    72,    72, 
    20052, 20088, 20124, 20160, 20196, 20232, 20268, 20304, 20340,    72, 
       72,    72, 20376, 20412, 20448, 20484, 20520, 20556, 20592, 20628, 
    20664,    72,    72, 20700, 20736, 20772,    72, 20808, 20844, 20880, 
    20916, 20952, 20988, 21024, 21060, 21096, 21132,    72,    72, 21168, 
    21204,    72, 21240, 21276, 21312,    72,    72, 21348, 21384, 21420, 
       72,    72, 21456,    72, 21492,    72,    72, 21528, 21564, 21600, 
       72, 21636, 21672, 21708, 21744,    72, 21780, 21816, 21852, 21888, 
       72, 21924,    72,    72,    72, 21960, 21996, 22032,    72,    72, 
       72, 22068, 22104,    72,    72, 22140,    72, 22176, 22212, 22248, 
    22284, 22320, 22356,    72, 22392,    72,    72
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\0\1\2\1\0\1\3\1\4\1\5\1\6\2\0"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\0\1\20\1\21\1\22\1\23\11\0\1\24"+
    "\1\25\6\0\1\26\1\27\2\0\1\30\1\31\1\0"+
    "\1\32\2\0\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\66\0\1\44\5\0\1\45\13\0"+
    "\1\46\34\0\1\47\32\0\1\50\11\0\1\51\34\0"+
    "\1\52\1\53\35\0\1\54\7\0\1\55\5\0\1\56"+
    "\24\0\1\57\17\0\1\60\1\61\14\0\1\62\14\0"+
    "\1\63\1\0\1\64\5\0\1\65\40\0\1\66\35\0"+
    "\1\67\2\0\1\70\1\0\1\71\1\0\1\72\1\0"+
    "\1\73\1\0\1\74\1\75\22\0\1\76\1\0\1\77"+
    "\3\0\1\100\1\0\1\101\3\0\1\102\27\0\1\103"+
    "\5\0\1\104\36\0\1\105\7\0\1\106\43\0\1\107"+
    "\32\0\1\110\5\0\1\111\1\0\1\112\3\0\1\113"+
    "\27\0\1\114\7\0\1\115\6\0\1\116\1\0\1\117"+
    "\27\0\1\120\2\0\1\121\1\122\46\0\1\123\35\0"+
    "\1\124\2\0\1\125\5\0\1\126\24\0\1\127\4\0"+
    "\1\130\53\0\1\131\1\0\1\132\23\0\1\133\1\134"+
    "\3\0\1\135\1\0\1\136\2\0\1\137\1\140\1\141"+
    "\1\142\1\143\1\144\1\145\1\146\1\147\22\0\1\150"+
    "\4\0\1\151\45\0\1\152\1\153\5\0\1\154\24\0"+
    "\1\155\1\0\1\156\3\0\1\157\1\160\12\0\1\161"+
    "\22\0\1\162\52\0\1\163\3\0\1\164\47\0\1\165"+
    "\40\0\1\166\37\0\1\167\40\0\1\170\4\0\1\171"+
    "\10\0\1\172\1\173\1\174\1\175\1\176\1\177\20\0"+
    "\1\200\56\0\1\201\40\0\1\202\2\0\1\203\22\0"+
    "\1\204\1\0\1\205\2\0\1\206\1\207\1\210\1\211"+
    "\1\212\1\213\4\0\1\214\1\215\1\216\11\0\1\217"+
    "\24\0\1\220\35\0\1\221\3\0\1\222\40\0\1\223"+
    "\55\0\1\224\56\0\1\225\27\0\1\226\14\0\1\227"+
    "\26\0\1\230\23\0\1\231\56\0\1\232\1\0\1\233"+
    "\41\0\1\234\5\0\1\235\37\0\1\236\34\0\1\237"+
    "\50\0\1\240\50\0\1\241\44\0\1\242\43\0\1\243"+
    "\42\0\1\244\26\0\1\245\3\0\1\246\73\0\1\247"+
    "\14\0\1\250\34\0\1\251\4\0\1\252\44\0\1\253"+
    "\52\0\1\254\43\0\1\255\25\0\1\256\5\0\1\257"+
    "\73\0\1\260\20\0\1\261\36\0\1\262\3\0\1\263"+
    "\21\0\1\264\17\0\1\265\65\0\1\266\21\0\1\267"+
    "\44\0\1\270\33\0\1\271\12\0\1\272\17\0\1\273"+
    "\7\0\1\274\13\0\1\275\34\0\1\276\52\0\1\277"+
    "\30\0\1\300\6\0\1\301\3\0\1\302\3\0\1\303"+
    "\43\0\1\304\32\0\1\305\1\0\1\306\41\0\1\307"+
    "\45\0\1\310\41\0\1\311\5\0\1\312\44\0\1\313"+
    "\27\0\1\314\61\0\1\315\41\0\1\316\42\0\1\317"+
    "\30\0\1\320\54\0\1\321\27\0\1\322\1\0\1\323"+
    "\60\0\1\324\1\0\1\325\24\0\1\326\4\0\1\327"+
    "\34\0\1\330\54\0\1\331\1\332\5\0\1\333\26\0"+
    "\1\334\3\0\1\335\1\336\12\0\1\337\22\0\1\340"+
    "\41\0\1\341\43\0\1\342\43\0\1\343\20\0\1\344"+
    "\40\0\1\345\37\0\1\346\45\0\1\347\10\0\1\350"+
    "\1\351\1\352\1\353\1\354\1\355\20\0\1\356\5\0"+
    "\1\357\36\0\1\360\43\0\1\361\54\0\1\362\23\0"+
    "\1\363\15\0\1\364\26\0\1\365\42\0\1\366\54\0"+
    "\1\367\37\0\1\370\61\0\1\371\36\0\1\372\41\0"+
    "\1\373\37\0\1\374\35\0\1\375\74\0\1\376\16\0"+
    "\1\377\36\0\1\u0100\62\0\1\u0101\23\0\1\u0102\44\0"+
    "\1\u0103\53\0\1\u0104\32\0\1\u0105\44\0\1\u0106\50\0"+
    "\1\u0107\54\0\1\u0108\40\0\1\u0109\30\0\1\u010a\62\0"+
    "\1\u010b\1\0\1\u010c\32\0\1\u010d\44\0\1\u010e\63\0"+
    "\1\u010f\20\0\1\u0110\44\0\1\u0111\44\0\1\u0112\44\0"+
    "\1\u0113\63\0\1\u0114\43\0\1\u0115\22\0\1\u0116\40\0"+
    "\1\u0117\67\0\1\u0118\25\0\1\u0119\6\0\1\u011a\35\0"+
    "\1\u011b\37\0\1\u011c\44\0\1\u011d\54\0\1\u011e\42\0"+
    "\1\u011f\34\0\1\u0120\43\0\1\u0121\62\0\1\u0122\22\0"+
    "\1\u0123\52\0\1\u0124\31\0\1\u0125\46\0\1\u0126\42\0"+
    "\1\u0127\51\0\1\u0128\26\0\1\u0129\60\0\1\u012a\35\0"+
    "\1\u012b\44\0\1\u012c\47\0\1\u012d\51\0\1\u012e\33\0"+
    "\1\u012f\50\0\1\u0130\34\0\1\u0131\54\0\1\u0132\27\0"+
    "\1\u0133\46\0\1\u0134\41\0\1\u0135\44\0\1\u0136\51\0"+
    "\1\u0137\50\0\1\u0138\32\0\1\u0139\42\0\1\u013a\55\0"+
    "\1\u013b\33\0\1\u013c\63\0\1\u013d\16\0\1\u013e\53\0"+
    "\1\u013f\40\0\1\u0140\31\0\1\u0141\10\0\1\u0142\51\0"+
    "\1\u0143\35\0\1\u0144\40\0\1\u0145\42\0\1\u0146\42\0"+
    "\1\u0147\40\0\1\u0148\64\0\1\u0149\27\0\1\u014a\47\0"+
    "\1\u014b\45\0\1\u014c\1\0\1\u014d\33\0\1\u014e\50\0"+
    "\1\u014f\32\0\1\u0150\55\0\1\u0151\30\0\1\u0152\54\0"+
    "\1\u0153\27\0\1\u0154\52\0\1\u0155\5\0\1\u0156\36\0"+
    "\1\u0157\43\0\1\u0158\54\0\1\u0159\23\0\1\u015a\15\0"+
    "\1\u015b\24\0\1\u015c\43\0\1\u015d\44\0\1\u015e\42\0"+
    "\1\u015f\51\0\1\u0160\35\0\1\u0161\43\0\1\u0162\60\0"+
    "\1\u0163\37\0\1\u0164\32\0\1\u0165\43\0\1\u0166\43\0"+
    "\1\u0167\43\0\1\u0168\43\0\1\u0169\43\0\1\u016a\54\0"+
    "\1\u016b\46\0\1\u016c\40\0\1\u016d\53\0\1\u016e\34\0"+
    "\1\u016f\34\0\1\u0170\61\0\1\u0171\32\0\1\u0172\42\0"+
    "\1\u0173\54\0\1\u0174\37\0\1\u0175\50\0\1\u0176\34\0"+
    "\1\u0177\55\0\1\u0178\21\0\1\u0179\62\0\1\u017a\42\0"+
    "\1\u017b\44\0\1\u017c\44\0\1\u017d\34\0\1\u017e\32\0"+
    "\1\u017f\61\0\1\u0180\32\0\1\u0181\35\0\1\u0182\63\0"+
    "\1\u0183\32\0\1\u0184\51\0\1\u0185\35\0\1\u0186\37\0"+
    "\1\u0187\46\0\1\u0188\35\0\1\u0189\54\0\1\u018a\64\0"+
    "\1\u018b\27\0\1\u018c\13\0\1\u018d\23\0\1\u018e\63\0"+
    "\1\u018f\44\0\1\u0190\24\0\1\u0191\30\0\1\u0192\54\0"+
    "\1\u0193\3\0\1\u0194\57\0\1\u0195\26\0\1\u0196\27\0"+
    "\1\u0197\57\0\1\u0198\31\0\1\u0199\61\0\1\u019a\33\0"+
    "\1\u019b\45\0\1\u019c\62\0\1\u019d\20\0\1\u019e\45\0"+
    "\1\u019f\52\0\1\u01a0\34\0\1\u01a1\41\0\1\u01a2\66\0"+
    "\1\u01a3\25\0\1\u01a4\40\0\1\u01a5\64\0\1\u01a6\22\0"+
    "\1\u01a7\44\0\1\u01a8\40\0\1\u01a9\43\0\1\u01aa\66\0"+
    "\1\u01ab\27\0\1\u01ac\34\0\1\u01ad\66\0\1\u01ae\13\0"+
    "\1\u01af\47\0\1\u01b0\55\0\1\u01b1\55\0\1\u01b2\21\0"+
    "\1\u01b3\65\0\1\u01b4\13\0\1\u01b5\50\0\1\u01b6\42\0"+
    "\1\u01b7\43\0\1\u01b8\53\0\1\u01b9\13\0\1\u01ba\23\0"+
    "\1\u01bb\3\0\1\u01bc\37\0\1\u01bd\37\0\1\u01be\36\0"+
    "\1\u01bf\10\0\1\u01c0\17\0\1\u01c1\31\0\1\u01c2\11\0"+
    "\1\u01c3\22\0\1\u01c4\54\0\1\u01c5\42\0\1\u01c6\44\0"+
    "\1\u01c7\44\0\1\u01c8\31\0\1\u01c9\53\0\1\u01ca\55\0"+
    "\1\u01cb\11\0\1\u01cc\45\0\1\u01cd\55\0\1\u01ce\36\0"+
    "\1\u01cf\46\0\1\u01d0\40\0\1\u01d1\53\0\1\u01d2\34\0"+
    "\1\u01d3\31\0\1\u01d4\43\0\1\u01d5\64\0\1\u01d6\31\0"+
    "\1\u01d7\50\0\1\u01d8\50\0\1\u01d9\34\0\1\u01da\52\0"+
    "\1\u01db\44\0\1\u01dc\25\0\1\u01dd\51\0\1\u01de\34\0"+
    "\1\u01df\50\0\1\u01e0\47\0\1\u01e1\41\0\1\u01e2\40\0"+
    "\1\u01e3\43\0\1\u01e4\53\0\1\u01e5\26\0\1\u01e6\50\0"+
    "\1\u01e7\56\0\1\u01e8\41\0\1\u01e9\35\0\1\u01ea\40\0"+
    "\1\u01eb\47\0\1\u01ec\32\0\1\u01ed\52\0\1\u01ee\34\0"+
    "\1\u01ef\44\0\1\u01f0\62\0\1\u01f1\36\0\1\u01f2\31\0"+
    "\1\u01f3\13\0\1\u01f4\1\u01f5\45\0\1\u01f6\42\0\1\u01f7"+
    "\35\0\1\u01f8\17\0\1\u01f9\20\0\1\u01fa\66\0\1\u01fb"+
    "\43\0\1\u01fc\43\0\1\u01fd\25\0\1\u01fe\41\0\1\u01ff"+
    "\44\0\1\u0200\44\0\1\u0201\31\0\1\u0202\57\0\1\u0203"+
    "\43\0\1\u0204\40\0\1\u0205\62\0\1\u0206\43\0\1\u0207"+
    "\17\0\1\u0208\67\0\1\u0209\31\0\1\u020a\55\0\1\u020b"+
    "\17\0\1\u020c\37\0\1\u020d\54\0\1\u020e\62\0\1\u020f"+
    "\26\0\1\u0210\30\0\1\u0211\57\0\1\u0212\43\0\1\u0213"+
    "\36\0\1\u0214\53\0\1\u0215\54\0\1\u0216\20\0\1\u0217"+
    "\46\0\1\u0218\52\0\1\u0219\23\0\1\u021a\74\0\1\u021b"+
    "\20\0\1\u021c\52\0\1\u021d\34\0\1\u021e\66\0\1\u021f"+
    "\43\0\1\u0220\16\0\1\u0221\47\0\1\u0222\41\0\1\u0223"+
    "\42\0\1\u0224\50\0\1\u0225\41\0\1\u0226\64\0\1\u0227"+
    "\25\0\1\u0228\61\0\1\u0229\22\0\1\u022a\64\0\1\u022b"+
    "\25\0\1\u022c\26\0\1\u022d\45\0\1\u022e\41\0\1\u022f"+
    "\43\0\1\u0230\55\0\1\u0231\52\0\1\u0232\44\0\1\u0233"+
    "\33\0\1\u0234\41\0\1\u0235\45\0\1\u0236\31\0\1\u0237"+
    "\56\0\1\u0238\44\0\1\u0239\40\0\1\u023a\41\0\1\u023b"+
    "\56\0\1\u023c\10\0\1\u023d\12\0\1\u023e\53\0\1\u023f"+
    "\40\0\1\u0240\67\0\1\u0241\31\0\1\u0242\35\0\1\u0243"+
    "\44\0\1\u0244\43\0\1\u0245\41\0\1\u0246\40\0\1\u0247"+
    "\52\0\1\u0248\35\0\1\u0249\66\0\1\u024a\44\0\1\u024b"+
    "\33\0\1\u024c\21\0\1\u024d\50\0\1\u024e\53\0\1\u024f"+
    "\57\0\1\u0250\22\0\1\u0251\50\0\1\u0252\41\0\1\u0253"+
    "\61\0\1\u0254\44\0\1\u0255\6\0\1\u0256\67\0\1\u0257"+
    "\11\0\1\u0258\41\0\1\u0259\31\0\1\u025a\34\0\1\u025b"+
    "\43\0\1\u025c\35\0\1\u025d\55\0\1\u025e\51\0\1\u025f"+
    "\31\0\1\u0260\64\0\1\u0261\50\0\1\u0262\15\0\1\u0263"+
    "\64\0\1\u0264\23\0\1\u0265\63\0\1\u0266\17\0\1\u0267"+
    "\67\0\1\u0268\24\0\1\u0269\50\0\1\u026a\37\0\1\u026b"+
    "\36\0\1\u026c\36\0\1\u026d\46\0\1\u026e\51\0\1\u026f"+
    "\44\0\1\u0270\41\0\1\u0271\63\0\1\u0272\43\0\1\u0273"+
    "\43\0\1\u0274\43\0\1\u0275\25\0\1\u0276\41\0\1\u0277"+
    "\30\0\1\u0278\57\0\1\u0279\27\0\1\u027a\54\0\1\u027b"+
    "\41\0\1\u027c\46\0\1\u027d\43\0\1\u027e\33\0\1\u027f"+
    "\61\0\1\u0280\32\0\1\u0281\67\0\1\u0282\26\0\1\u0283"+
    "\60\0\1\u0284\43\0\1\u0285\43\0\1\u0286\12\0\1\u0287"+
    "\1\u0288\5\0\1\u0289\6\0\1\u028a\56\0\1\u028b\24\0"+
    "\1\u028c\32\0\1\u028d\73\0\1\u028e\22\0\1\u028f\66\0"+
    "\1\u0290\20\0\1\u0291\64\0\1\u0292\13\0\1\u0293\50\0"+
    "\1\u0294\66\0\1\u0295\22\0\1\u0296\53\0\1\u0297\33\0"+
    "\1\u0298\47\0\1\u0299\37\0\1\u029a\64\0\1\u029b\13\0"+
    "\1\u029c\73\0\1\u029d\25\0\1\u029e\44\0\1\u029f\64\0"+
    "\1\u02a0\16\0\1\u02a1\53\0\1\u02a2\45\0\1\u02a3\32\0"+
    "\1\u02a4\63\0\1\u02a5\32\0\1\u02a6\24\0\1\u02a7\73\0"+
    "\1\u02a8\43\0\1\u02a9\34\0\1\u02aa\52\0\1\u02ab\10\0"+
    "\1\u02ac\55\0\1\u02ad\31\0\1\u02ae\55\0\1\u02af\31\0"+
    "\1\u02b0\57\0\1\u02b1\42\0\1\u02b2\51\0\1\u02b3\37\0"+
    "\1\u02b4\42\0\1\u02b5\51\0\1\u02b6\41\0\1\u02b7\15\0"+
    "\1\u02b8\7\0\1\u02b9\43\0\1\u02ba\60\0\1\u02bb\57\0"+
    "\1\u02bc\43\0\1\u02bd\43\0\1\u02be\25\0\1\u02bf\41\0"+
    "\1\u02c0\52\0\1\u02c1\25\0\1\u02c2\62\0\1\u02c3\36\0"+
    "\1\u02c4\30\0\1\u02c5\64\0\1\u02c6\34\0\1\u02c7\61\0"+
    "\1\u02c8\43\0\1\u02c9\26\0\1\u02ca\43\0\1\u02cb\43\0"+
    "\1\u02cc\60\0\1\u02cd\24\0\1\u02ce\42\0\1\u02cf\32\0"+
    "\1\u02d0\44\0\1\u02d1\56\0\1\u02d2\61\0\1\u02d3\23\0"+
    "\1\u02d4\41\0\1\u02d5\66\0\1\u02d6\44\0\1\u02d7\40\0"+
    "\1\u02d8\43\0\1\u02d9\23\0\1\u02da\46\0\1\u02db\60\0"+
    "\1\u02dc\20\0\1\u02dd\57\0\1\u02de\33\0\1\u02df\62\0"+
    "\1\u02e0\43\0\1\u02e1\25\0\1\u02e2\43\0\1\u02e3\43\0"+
    "\1\u02e4\26\0\1\u02e5\43\0\1\u02e6\52\0\1\u02e7\67\0"+
    "\1\u02e8\22\0\1\u02e9\64\0\1\u02ea\43\0\1\u02eb\17\0"+
    "\1\u02ec\51\0\1\u02ed\40\0\1\u02ee\64\0\1\u02ef\25\0"+
    "\1\u02f0\35\0\1\u02f1\57\0\1\u02f2\43\0\1\u02f3\53\0"+
    "\1\u02f4\34\0\1\u02f5\43\0\1\u02f6\22\0\1\u02f7\15\0"+
    "\1\u02f8\11\0\1\u02f9\23\0\1\u02fa\63\0\1\u02fb\43\0"+
    "\1\u02fc\43\0\1\u02fd\34\0\1\u02fe\40\0\1\u02ff\36\0"+
    "\1\u0300\62\0\1\u0301\43\0\1\u0302\43\0\1\u0303\20\0"+
    "\1\u0304\51\0\1\u0305\60\0\1\u0306\43\0\1\u0307\26\0"+
    "\1\u0308\60\0\1\u0309\17\0\1\u030a\60\0\1\u030b\32\0"+
    "\1\u030c\64\0\1\u030d\32\0\1\u030e\34\0\1\u030f\62\0"+
    "\1\u0310\24\0\1\u0311\62\0\1\u0312\43\0\1\u0313\5\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  1,  0,  0,  0,  9,  0,  0,  0,  1,  9,  1, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  9,  0,  9,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  9,  0, 
     1,  0,  0,  0,  9,  9,  0,  9,  0,  9,  9,  9,  9,  9,  9,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  9,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0, 
     9,  9,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  9,  9,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0, 
     0,  0,  0,  9,  9,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9, 
     0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  9,  9,  0,  9,  0, 
     9,  9,  0,  0,  9,  9,  9,  9,  9,  9,  9,  9,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  9,  0,  9,  0, 
     0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0, 
     0,  0,  9,  0,  0,  9,  0,  0,  0,  0,  9,  9,  0,  9,  0,  0, 
     0,  9,  0,  9,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0, 
     9,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  9,  9,  0,  0,  0,  0,  1,  9,  0,  9,  9,  9,  0, 
     9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  9,  9,  9,  0,  0,  0, 
     0,  0,  0,  0,  0,  9,  9,  0,  9,  0,  9,  0,  0,  0,  9,  0, 
     0,  9,  0,  0,  0,  9,  0,  0,  0,  0,  9,  0,  0,  0,  9,  9, 
     0,  0,  0,  0,  0,  0,  9,  0,  9,  0,  9,  9,  9,  0,  9,  9, 
     0,  0,  0,  0,  0,  0,  9,  0,  9,  0,  9,  0,  9,  0,  0,  0, 
     9,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  9, 
     0,  0,  0,  9,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0, 
     9,  0,  9,  9,  0,  9,  0,  9,  9,  0,  0,  0,  0,  0,  0,  0, 
     0,  9,  9,  9,  9,  0,  0,  9,  0,  9,  0,  0,  0,  0,  0,  0, 
     0,  9,  0,  9,  9,  9,  0,  0,  0,  0,  9,  0,  0,  9,  0,  0, 
     0,  9,  9,  0,  9,  0,  0,  0,  0,  9,  9,  9,  9,  0,  0,  0, 
     9,  0,  0,  9,  9,  0,  0,  9,  9,  0,  9,  9,  0,  9,  0,  9, 
     9,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  9,  9,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  9,  9,  0,  0,  0,  9,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  9,  9,  0,  0,  9,  0,  0,  0,  9, 
     9,  0,  0,  0,  9,  9,  0,  9,  0,  9,  9,  0,  0,  0,  9,  0, 
     0,  0,  0,  9,  0,  0,  0,  0,  9,  0,  9,  9,  9,  0,  0,  0, 
     9,  9,  9,  0,  0,  9,  9,  0,  9,  0,  0,  0,  0,  0,  0,  9, 
     0,  9,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    StringBuffer string = new StringBuffer();

    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[22428];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 94) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 770: 
          {  return symbol(sym.cellpadding);  }
        case 788: break;
        case 769: 
          {  return symbol(sym.cellspacing);  }
        case 789: break;
        case 768: 
          {  return symbol(sym.marginwidth);  }
        case 790: break;
        case 764: 
          {  return symbol(sym.onmousemove);  }
        case 791: break;
        case 763: 
          {  return symbol(sym.onmousedown);  }
        case 792: break;
        case 762: 
          {  return symbol(sym.onmouseover);  }
        case 793: break;
        case 760: 
          {  return symbol(sym.bordercolor);  }
        case 794: break;
        case 755: 
          {  return symbol(sym.leftmargin);  }
        case 795: break;
        case 750: 
          {  return symbol(sym.onkeypress);  }
        case 796: break;
        case 746: 
          {  return symbol(sym.onmouseout);  }
        case 797: break;
        case 745: 
          {  return symbol(sym.ondblclick);  }
        case 798: break;
        case 743: 
          {  return symbol(sym.background);  }
        case 799: break;
        case 555: 
          {  return symbol(sym.optionOpen);  }
        case 800: break;
        case 568: 
          {  return symbol(sym.selectOpen);  }
        case 801: break;
        case 570: 
          {  return symbol(sym.centerOpen);  }
        case 802: break;
        case 631: 
          {  return symbol(sym.smallClose);  }
        case 803: break;
        case 633: 
          {  return symbol(sym.tableClose);  }
        case 804: break;
        case 683: 
          {  return symbol(sym.optionClose);  }
        case 805: break;
        case 685: 
          {  return symbol(sym.selectClose);  }
        case 806: break;
        case 687: 
          {  return symbol(sym.centerClose);  }
        case 807: break;
        case 736: 
          {  return symbol(sym.topmargin);  }
        case 808: break;
        case 735: 
          {  return symbol(sym.scrolling);  }
        case 809: break;
        case 731: 
          {  return symbol(sym.accesskey);  }
        case 810: break;
        case 728: 
          {  return symbol(sym.onkeydown);  }
        case 811: break;
        case 727: 
          {  return symbol(sym.onmouseup);  }
        case 812: break;
        case 716: 
          {  return symbol(sym.hreflang);  }
        case 813: break;
        case 712: 
          {  return symbol(sym.longdesc);  }
        case 814: break;
        case 477: 
          {  return symbol(sym.tableOpen);  }
        case 815: break;
        case 474: 
          {  return symbol(sym.smallOpen);  }
        case 816: break;
        case 473: 
          {  return symbol(sym.frameOpen);  }
        case 817: break;
        case 468: 
          {  return symbol(sym.supClose);  }
        case 818: break;
        case 467: 
          {  return symbol(sym.subClose);  }
        case 819: break;
        case 373: 
          {  return symbol(sym.htmlOpen);  }
        case 820: break;
        case 363: 
          {  return symbol(sym.fontOpen);  }
        case 821: break;
        case 362: 
          {  return symbol(sym.formOpen);  }
        case 822: break;
        case 335: 
          {  return symbol(sym.bodyOpen);  }
        case 823: break;
        case 556: 
          {  return symbol(sym.bodyClose);  }
        case 824: break;
        case 558: 
          {  return symbol(sym.formClose);  }
        case 825: break;
        case 559: 
          {  return symbol(sym.fontClose);  }
        case 826: break;
        case 566: 
          {  return symbol(sym.htmlClose);  }
        case 827: break;
        case 658: 
          {  return symbol(sym.disabled);  }
        case 828: break;
        case 665: 
          {  return symbol(sym.multiple);  }
        case 829: break;
        case 667: 
          {  return symbol(sym.selected);  }
        case 830: break;
        case 672: 
          {  return symbol(sym.noresize);  }
        case 831: break;
        case 675: 
          {  return symbol(sym.controls);  }
        case 832: break;
        case 699: 
          {  return symbol(sym.onsubmit);  }
        case 833: break;
        case 700: 
          {  return symbol(sym.onunload);  }
        case 834: break;
        case 701: 
          {  return symbol(sym.onchange);  }
        case 835: break;
        case 711: 
          {  return symbol(sym.tabindex);  }
        case 836: break;
        case 448: 
          {  return symbol(sym.chr);  }
        case 837: break;
        case 119: 
          {  return symbol(sym.hr);  }
        case 838: break;
        case 87: 
          {  return symbol(sym.br);  }
        case 839: break;
        case 181: 
          {  return symbol(sym.id);  }
        case 840: break;
        case 248: 
          {  return symbol(sym.img);  }
        case 841: break;
        case 270: 
          {  return symbol(sym.dir);  }
        case 842: break;
        case 275: 
          {  return symbol(sym.rel);  }
        case 843: break;
        case 276: 
          {  return symbol(sym.rev);  }
        case 844: break;
        case 279: 
          {  return symbol(sym.alt);  }
        case 845: break;
        case 289: 
          {  return symbol(sym.src);  }
        case 846: break;
        case 542: 
          {  return symbol(sym.cls);  }
        case 847: break;
        case 776: 
          {  return symbol(sym.marginheight);  }
        case 848: break;
        case 774: 
          {  return symbol(sym.framespacing);  }
        case 849: break;
        case 773: 
          {  return symbol(sym.bgproperties);  }
        case 850: break;
        case 741: 
          {  return symbol(sym.noframesClose);  }
        case 851: break;
        case 740: 
          {  return symbol(sym.framesetClose);  }
        case 852: break;
        case 688: 
          {  return symbol(sym.framesetOpen);  }
        case 853: break;
        case 689: 
          {  return symbol(sym.noframesOpen);  }
        case 854: break;
        case 476: 
          {  return symbol(sym.tbody);  }
        case 855: break;
        case 450: 
          {  return symbol(sym.href);  }
        case 856: break;
        case 441: 
          {  return symbol(sym.cols);  }
        case 857: break;
        case 435: 
          {  return symbol(sym.link);  }
        case 858: break;
        case 433: 
          {  return symbol(sym.lang);  }
        case 859: break;
        case 429: 
          {  return symbol(sym.loop);  }
        case 860: break;
        case 427: 
          {  return symbol(sym.ismap);  }
        case 861: break;
        case 426: 
          {  return symbol(sym.name);  }
        case 862: break;
        case 421: 
          {  return symbol(sym.text);  }
        case 863: break;
        case 418: 
          {  return symbol(sym.type);  }
        case 864: break;
        case 412: 
          {  return symbol(sym.size);  }
        case 865: break;
        case 404: 
          {  return symbol(sym.axis);  }
        case 866: break;
        case 398: 
          {  return symbol(sym.abbr);  }
        case 867: break;
        case 396: 
          {  return symbol(sym.rows);  }
        case 868: break;
        case 394: 
          {  return symbol(sym.face);  }
        case 869: break;
        case 21: 
          {  return symbol(sym.bOpen);  }
        case 870: break;
        case 25: 
          {  return symbol(sym.aOpen);  }
        case 871: break;
        case 29: 
          {  return symbol(sym.iOpen);  }
        case 872: break;
        case 30: 
          {  return symbol(sym.pOpen);  }
        case 873: break;
        case 31: 
          {  return symbol(sym.uOpen);  }
        case 874: break;
        case 480: 
          {  return symbol(sym.input);  }
        case 875: break;
        case 504: 
          {  return symbol(sym.frame);  }
        case 876: break;
        case 506: 
          {  return symbol(sym.rules);  }
        case 877: break;
        case 507: 
          {  return symbol(sym.alink);  }
        case 878: break;
        case 508: 
          {  return symbol(sym.align);  }
        case 879: break;
        case 517: 
          {  return symbol(sym.style);  }
        case 880: break;
        case 518: 
          {  return symbol(sym.start);  }
        case 881: break;
        case 520: 
          {  return symbol(sym.scope);  }
        case 882: break;
        case 522: 
          {  return symbol(sym.shape);  }
        case 883: break;
        case 526: 
          {  return symbol(sym.title);  }
        case 884: break;
        case 533: 
          {  return symbol(sym.label);  }
        case 885: break;
        case 538: 
          {  return symbol(sym.color);  }
        case 886: break;
        case 543: 
          {  return symbol(sym.clear);  }
        case 887: break;
        case 550: 
          {  return symbol(sym.width);  }
        case 888: break;
        case 552: 
          {  return symbol(sym.value);  }
        case 889: break;
        case 554: 
          {  return symbol(sym.vlink);  }
        case 890: break;
        case 786: 
          {  return symbol(sym.bordercolorlight);  }
        case 891: break;
        case 785: 
          {  return symbol(sym.acceptcharlist);  }
        case 892: break;
        case 783: 
          {  return symbol(sym.bordercolordark);  }
        case 893: break;
        case 361: 
          {  return symbol(sym.h6Close);  }
        case 894: break;
        case 360: 
          {  return symbol(sym.h5Close);  }
        case 895: break;
        case 359: 
          {  return symbol(sym.h4Close);  }
        case 896: break;
        case 358: 
          {  return symbol(sym.h3Close);  }
        case 897: break;
        case 357: 
          {  return symbol(sym.h2Close);  }
        case 898: break;
        case 356: 
          {  return symbol(sym.h1Close);  }
        case 899: break;
        case 353: 
          {  return symbol(sym.liClose);  }
        case 900: break;
        case 352: 
          {  return symbol(sym.ulClose);  }
        case 901: break;
        case 350: 
          {  return symbol(sym.thClose);  }
        case 902: break;
        case 348: 
          {  return symbol(sym.trClose);  }
        case 903: break;
        case 347: 
          {  return symbol(sym.tdClose);  }
        case 904: break;
        case 339: 
          {  return symbol(sym.olClose);  }
        case 905: break;
        case 123: 
          {  return symbol(sym.h3Open);  }
        case 906: break;
        case 122: 
          {  return symbol(sym.h2Open);  }
        case 907: break;
        case 121: 
          {  return symbol(sym.h1Open);  }
        case 908: break;
        case 117: 
          {  return symbol(sym.liOpen);  }
        case 909: break;
        case 116: 
          {  return symbol(sym.ulOpen);  }
        case 910: break;
        case 112: 
          {  return symbol(sym.thOpen);  }
        case 911: break;
        case 110: 
          {  return symbol(sym.trOpen);  }
        case 912: break;
        case 109: 
          {  return symbol(sym.tdOpen);  }
        case 913: break;
        case 2: 
          {  return symbol(sym.endTag);  }
        case 914: break;
        case 89: 
          {  return symbol(sym.olOpen);  }
        case 915: break;
        case 124: 
          {  return symbol(sym.h4Open);  }
        case 916: break;
        case 125: 
          {  return symbol(sym.h5Open);  }
        case 917: break;
        case 126: 
          {  return symbol(sym.h6Open);  }
        case 918: break;
        case 209: 
          {  return symbol(sym.bClose);  }
        case 919: break;
        case 215: 
          {  return symbol(sym.aClose);  }
        case 920: break;
        case 224: 
          {  return symbol(sym.iClose);  }
        case 921: break;
        case 225: 
          {  return symbol(sym.pClose);  }
        case 922: break;
        case 226: 
          {  return symbol(sym.uClose);  }
        case 923: break;
        case 242: 
          {  return symbol(sym.subOpen);  }
        case 924: break;
        case 243: 
          {  return symbol(sym.supOpen);  }
        case 925: break;
        case 478: 
          {  return symbol(sym.thread);  }
        case 926: break;
        case 529: 
          {  return symbol(sym.nowrap);  }
        case 927: break;
        case 572: 
          {  return symbol(sym.border);  }
        case 928: break;
        case 576: 
          {  return symbol(sym.onblur);  }
        case 929: break;
        case 585: 
          {  return symbol(sym.onload);  }
        case 930: break;
        case 591: 
          {  return symbol(sym.dynsrc);  }
        case 931: break;
        case 595: 
          {  return symbol(sym.action);  }
        case 932: break;
        case 600: 
          {  return symbol(sym.method);  }
        case 933: break;
        case 608: 
          {  return symbol(sym.target);  }
        case 934: break;
        case 610: 
          {  return symbol(sym.noshade);  }
        case 935: break;
        case 611: 
          {  return symbol(sym.usemap);  }
        case 936: break;
        case 613: 
          {  return symbol(sym.lowsrc);  }
        case 937: break;
        case 615: 
          {  return symbol(sym.coords);  }
        case 938: break;
        case 616: 
          {  return symbol(sym.compact);  }
        case 939: break;
        case 625: 
          {  return symbol(sym.height);  }
        case 940: break;
        case 626: 
          {  return symbol(sym.hspace);  }
        case 941: break;
        case 627: 
          {  return symbol(sym.valign);  }
        case 942: break;
        case 628: 
          {  return symbol(sym.vspace);  }
        case 943: break;
        case 641: 
          {  return symbol(sym.bgcolor);  }
        case 944: break;
        case 643: 
          {  return symbol(sym.onfocus);  }
        case 945: break;
        case 644: 
          {  return symbol(sym.onreset);  }
        case 946: break;
        case 645: 
          {  return symbol(sym.onabort);  }
        case 947: break;
        case 650: 
          {  return symbol(sym.onerror);  }
        case 948: break;
        case 653: 
          {  return symbol(sym.onclick);  }
        case 949: break;
        case 657: 
          {  return symbol(sym.onkeyup);  }
        case 950: break;
        case 660: 
          {  return symbol(sym.rowspan);  }
        case 951: break;
        case 666: 
          {  return symbol(sym.enctype);  }
        case 952: break;
        case 668: 
          {  return symbol(sym.summary);  }
        case 953: break;
        case 676: 
          {  return symbol(sym.colspan);  }
        case 954: break;
        case 679: 
          {  return symbol(sym.charoff);  }
        case 955: break;
        case 680: 
          {  return symbol(sym.charset);  }
        case 956: break;
        case 682: 
          {  return symbol(sym.headers);  }
        case 957: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
