/* The following code was generated by JFlex 1.3.5 on 11/1/20, 6:33 PM */

    
import java_cup.runtime.Symbol;
    

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 11/1/20, 6:33 PM from the specification file
 * <tt>file:/C:/Users/Victor/eclipse-workspace/LexerHTML/lexer.jflex</tt>
 */
class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\41\0\1\0\10\0\1\0\2\0\1\2\1\0\1\10\1\0\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\5\0\1\1\1\36\1\3\42\0"+
    "\1\13\1\4\1\25\1\6\1\15\1\11\1\27\1\26\1\21\1\0"+
    "\1\37\1\24\1\14\1\20\1\5\1\22\1\0\1\12\1\16\1\17"+
    "\1\23\1\41\1\40\1\42\1\7\1\43\uff85\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    36,    72,   108,   144,   180,   216,   252,   288,   324, 
      360,   396,   432,   468,   504,   540,   576,   612,   648,   684, 
      720,   756,   792,   828,   864,    72,   900,   936,   972,  1008, 
       72,  1044,  1080,  1116,  1152,  1188,  1224,  1260,  1296,  1332, 
     1368,  1404,  1440,  1476,  1512,  1548,  1584,  1620,  1656,  1692, 
     1728,  1764,  1800,  1836,  1872,  1908,  1944,  1980,  2016,  2052, 
     2088,  2124,  2160,  2196,  2232,  2268,  2304,  2340,  2376,  2412, 
     2448,  2484,  2520,  2556,  2592,  2628,  2664,  2700,  2736,  2772, 
     2808,  2844,  2880,  2916,  2952,  2988,  3024,    72,  3060,    72, 
     3096,  3132,  3168,    72,  3204,  3240,  3276,    72,  3312,  3348, 
     3384,  3420,  3456,  3492,  3528,  3564,  3600,  3636,  3672,    72, 
       72,  3708,  3744,  3780,  3816,  3852,    72,    72,  3888,    72, 
     3924,    72,    72,    72,    72,    72,    72,  3960,  3996,  4032, 
     4068,  4104,  4140,  4176,  4212,  4248,  4284,  4320,  4356,  4392, 
     4428,  4464,  4500,  4536,  4572,  4608,  4644,  4680,  4716,  4752, 
     4788,  4824,  4860,  4896,  4932,  4968,  5004,  5040,  5076,  5112, 
     5148,  5184,  5220,  5256,  5292,  5328,  5364,  5400,  5436,  5472, 
     5508,  5544,  5580,  5616,  5652,  5688,  5724,  5760,  5796,  5832, 
     5868,    72,  5904,  5940,  5976,  6012,  6048,  6084,  6120,  6156, 
     6192,  6228,  6264,  6300,  6336,  6372,  6408,  6444,  6480,  6516, 
     6552,  6588,  6624,  6660,  6696,  6732,  6768,  6804,  6840,  6876, 
     6912,    72,  6948,  6984,  7020,  7056,  7092,    72,    72,  7128, 
       72,  7164,    72,    72,    72,  7200,  7236,    72,    72,    72, 
       72,    72,    72,  7272,  7308,  7344,  7380,  7416,    72,    72, 
     7452,  7488,  7524,  7560,    72,  7596,  7632,  7668,  7704,  7740, 
     7776,  7812,  7848,  7884,  7920,  7956,  7992,  8028,  8064,  8100, 
     8136,  8172,  8208,  8244,  8280,  8316,    72,  8352,  8388,  8424, 
     8460,    72,    72,  8496,  8532,    72,  8568,  8604,  8640,  8676, 
     8712,  8748,  8784,  8820,  8856,    72,  8892,  8928,  8964,  9000, 
     9036,  9072,  9108,  9144,  9180,  9216,  9252,  9288,  9324,  9360, 
     9396,  9432,  9468,  9504,  9540,  9576,  9612,  9648,  9684,  9720, 
     9756,  9792,  9828,  9864,  9900,  9936,  9972, 10008, 10044, 10080, 
    10116, 10152, 10188, 10224, 10260, 10296, 10332, 10368, 10404, 10440, 
    10476,    72, 10512, 10548, 10584, 10620, 10656, 10692, 10728, 10764, 
       72,    72, 10800, 10836, 10872, 10908,    72,    72, 10944, 10980, 
    11016, 11052, 11088, 11124, 11160, 11196, 11232,    72, 11268, 11304, 
    11340, 11376, 11412, 11448, 11484, 11520, 11556, 11592, 11628, 11664, 
    11700, 11736, 11772, 11808, 11844, 11880, 11916, 11952,    72, 11988, 
       72, 12024,    72, 12060, 12096, 12132, 12168, 12204,    72, 12240, 
    12276, 12312, 12348, 12384, 12420, 12456,    72, 12492, 12528, 12564, 
    12600, 12636,    72, 12672, 12708,    72, 12744, 12780, 12816, 12852, 
       72,    72, 12888,    72, 12924, 12960, 12996,    72, 13032,    72, 
    13068, 13104, 13140, 13176, 13212,    72, 13248, 13284, 13320, 13356, 
    13392, 13428,    72, 13464,    72, 13500, 13536, 13572, 13608, 13644, 
    13680, 13716, 13752, 13788,    72, 13824,    72,    72, 13860, 13896, 
    13932, 13968, 14004, 14040,    72, 14076,    72, 14112,    72,    72, 
       72, 14148,    72, 14184, 14220, 14256, 14292, 14328, 14364, 14400, 
    14436, 14472, 14508, 14544, 14580, 14616, 14652, 14688, 14724, 14760, 
    14796, 14832, 14868, 14904, 14940, 14976,    72, 15012,    72,    72, 
       72, 15048, 15084, 15120, 15156, 15192, 15228, 15264, 15300,    72, 
       72, 15336,    72, 15372,    72, 15408, 15444, 15480,    72, 15516, 
    15552,    72, 15588, 15624, 15660,    72, 15696, 15732, 15768, 15804, 
       72, 15840, 15876, 15912,    72,    72, 15948, 15984, 16020, 16056, 
    16092, 16128,    72, 16164,    72, 16200,    72,    72, 16236, 16272, 
       72, 16308,    72, 16344, 16380, 16416,    72, 16452,    72, 16488, 
       72, 16524, 16560, 16596,    72, 16632, 16668, 16704, 16740, 16776, 
    16812, 16848, 16884,    72, 16920, 16956, 16992, 17028, 17064,    72, 
    17100, 17136, 17172,    72, 17208, 17244, 17280, 17316,    72, 17352, 
    17388, 17424, 17460, 17496, 17532, 17568,    72, 17604,    72,    72, 
    17640,    72, 17676,    72,    72, 17712, 17748, 17784, 17820, 17856, 
    17892, 17928, 17964,    72,    72,    72,    72,    72, 18000,    72, 
    18036,    72, 18072, 18108, 18144, 18180, 18216,    72, 18252,    72, 
       72,    72, 18288, 18324, 18360, 18396,    72, 18432, 18468,    72, 
    18504, 18540, 18576,    72,    72, 18612,    72, 18648, 18684, 18720, 
    18756,    72,    72,    72,    72, 18792, 18828, 18864,    72, 18900, 
    18936,    72,    72, 18972, 19008,    72,    72, 19044,    72, 19080, 
    19116,    72,    72, 19152, 19188, 19224, 19260, 19296, 19332, 19368, 
    19404, 19440,    72,    72,    72, 19476, 19512, 19548, 19584, 19620, 
    19656, 19692, 19728, 19764,    72,    72, 19800, 19836, 19872,    72, 
       72,    72, 19908, 19944, 19980, 20016, 20052, 20088, 20124, 20160, 
       72,    72, 20196, 20232,    72, 20268, 20304, 20340,    72,    72, 
    20376, 20412, 20448, 20484,    72, 20520,    72,    72, 20556, 20592, 
    20628,    72, 20664, 20700, 20736, 20772,    72, 20808, 20844, 20880, 
    20916,    72, 20952,    72,    72,    72, 20988, 21024, 21060,    72, 
       72,    72, 21096, 21132,    72,    72, 21168,    72, 21204, 21240, 
    21276, 21312, 21348, 21384,    72, 21420,    72,    72
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\0\1\2\1\0\1\3\1\4\1\5\1\6\2\0"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\0\1\20\1\21\1\22\1\23\11\0\1\24"+
    "\1\25\6\0\1\26\1\27\2\0\1\30\1\31\1\0"+
    "\1\32\2\0\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\66\0\1\44\5\0\1\45\13\0"+
    "\1\46\34\0\1\47\32\0\1\50\11\0\1\51\34\0"+
    "\1\52\1\53\35\0\1\54\7\0\1\55\5\0\1\56"+
    "\24\0\1\57\17\0\1\60\1\61\14\0\1\62\14\0"+
    "\1\63\1\0\1\64\5\0\1\65\40\0\1\66\35\0"+
    "\1\67\2\0\1\70\1\0\1\71\1\0\1\72\1\0"+
    "\1\73\1\0\1\74\1\75\22\0\1\76\1\0\1\77"+
    "\3\0\1\100\1\0\1\101\3\0\1\102\27\0\1\103"+
    "\5\0\1\104\36\0\1\105\7\0\1\106\43\0\1\107"+
    "\32\0\1\110\5\0\1\111\1\0\1\112\3\0\1\113"+
    "\27\0\1\114\7\0\1\115\6\0\1\116\1\0\1\117"+
    "\27\0\1\120\2\0\1\121\1\122\46\0\1\123\35\0"+
    "\1\124\2\0\1\125\5\0\1\126\24\0\1\127\4\0"+
    "\1\130\53\0\1\131\1\0\1\132\23\0\1\133\1\134"+
    "\3\0\1\135\1\0\1\136\2\0\1\137\1\140\1\141"+
    "\1\142\1\143\1\144\1\145\1\146\1\147\22\0\1\150"+
    "\4\0\1\151\45\0\1\152\1\153\5\0\1\154\24\0"+
    "\1\155\1\0\1\156\3\0\1\157\1\160\12\0\1\161"+
    "\22\0\1\162\52\0\1\163\3\0\1\164\47\0\1\165"+
    "\40\0\1\166\37\0\1\167\40\0\1\170\4\0\1\171"+
    "\10\0\1\172\1\173\1\174\1\175\1\176\1\177\20\0"+
    "\1\200\56\0\1\201\40\0\1\202\2\0\1\203\22\0"+
    "\1\204\1\0\1\205\2\0\1\206\1\207\1\210\1\211"+
    "\1\212\1\213\4\0\1\214\1\215\1\216\11\0\1\217"+
    "\24\0\1\220\35\0\1\221\3\0\1\222\40\0\1\223"+
    "\55\0\1\224\56\0\1\225\27\0\1\226\14\0\1\227"+
    "\26\0\1\230\23\0\1\231\56\0\1\232\1\0\1\233"+
    "\41\0\1\234\5\0\1\235\37\0\1\236\34\0\1\237"+
    "\50\0\1\240\50\0\1\241\44\0\1\242\43\0\1\243"+
    "\42\0\1\244\26\0\1\245\3\0\1\246\73\0\1\247"+
    "\14\0\1\250\34\0\1\251\4\0\1\252\44\0\1\253"+
    "\52\0\1\254\43\0\1\255\25\0\1\256\5\0\1\257"+
    "\73\0\1\260\20\0\1\261\36\0\1\262\3\0\1\263"+
    "\21\0\1\264\17\0\1\265\65\0\1\266\21\0\1\267"+
    "\44\0\1\270\33\0\1\271\12\0\1\272\17\0\1\273"+
    "\7\0\1\274\13\0\1\275\34\0\1\276\52\0\1\277"+
    "\30\0\1\300\6\0\1\301\3\0\1\302\3\0\1\303"+
    "\43\0\1\304\32\0\1\305\1\0\1\306\41\0\1\307"+
    "\45\0\1\310\41\0\1\311\5\0\1\312\44\0\1\313"+
    "\27\0\1\314\61\0\1\315\41\0\1\316\42\0\1\317"+
    "\30\0\1\320\54\0\1\321\31\0\1\322\60\0\1\323"+
    "\1\0\1\324\24\0\1\325\4\0\1\326\45\0\1\327"+
    "\1\330\5\0\1\331\26\0\1\332\3\0\1\333\1\334"+
    "\12\0\1\335\22\0\1\336\41\0\1\337\64\0\1\340"+
    "\40\0\1\341\37\0\1\342\45\0\1\343\10\0\1\344"+
    "\1\345\1\346\1\347\1\350\1\351\20\0\1\352\5\0"+
    "\1\353\36\0\1\354\43\0\1\355\54\0\1\356\23\0"+
    "\1\357\15\0\1\360\26\0\1\361\42\0\1\362\54\0"+
    "\1\363\37\0\1\364\61\0\1\365\36\0\1\366\41\0"+
    "\1\367\37\0\1\370\35\0\1\371\74\0\1\372\16\0"+
    "\1\373\36\0\1\374\62\0\1\375\23\0\1\376\44\0"+
    "\1\377\53\0\1\u0100\32\0\1\u0101\44\0\1\u0102\50\0"+
    "\1\u0103\54\0\1\u0104\40\0\1\u0105\30\0\1\u0106\62\0"+
    "\1\u0107\1\0\1\u0108\32\0\1\u0109\44\0\1\u010a\63\0"+
    "\1\u010b\20\0\1\u010c\44\0\1\u010d\44\0\1\u010e\44\0"+
    "\1\u010f\63\0\1\u0110\43\0\1\u0111\22\0\1\u0112\40\0"+
    "\1\u0113\67\0\1\u0114\25\0\1\u0115\6\0\1\u0116\35\0"+
    "\1\u0117\37\0\1\u0118\44\0\1\u0119\54\0\1\u011a\42\0"+
    "\1\u011b\34\0\1\u011c\43\0\1\u011d\62\0\1\u011e\22\0"+
    "\1\u011f\52\0\1\u0120\31\0\1\u0121\46\0\1\u0122\42\0"+
    "\1\u0123\51\0\1\u0124\26\0\1\u0125\60\0\1\u0126\35\0"+
    "\1\u0127\44\0\1\u0128\47\0\1\u0129\51\0\1\u012a\33\0"+
    "\1\u012b\50\0\1\u012c\34\0\1\u012d\54\0\1\u012e\27\0"+
    "\1\u012f\46\0\1\u0130\41\0\1\u0131\44\0\1\u0132\51\0"+
    "\1\u0133\50\0\1\u0134\32\0\1\u0135\42\0\1\u0136\55\0"+
    "\1\u0137\33\0\1\u0138\63\0\1\u0139\16\0\1\u013a\53\0"+
    "\1\u013b\40\0\1\u013c\31\0\1\u013d\10\0\1\u013e\51\0"+
    "\1\u013f\35\0\1\u0140\40\0\1\u0141\42\0\1\u0142\42\0"+
    "\1\u0143\40\0\1\u0144\64\0\1\u0145\27\0\1\u0146\47\0"+
    "\1\u0147\45\0\1\u0148\1\0\1\u0149\33\0\1\u014a\50\0"+
    "\1\u014b\32\0\1\u014c\55\0\1\u014d\30\0\1\u014e\54\0"+
    "\1\u014f\36\0\1\u0150\5\0\1\u0151\36\0\1\u0152\43\0"+
    "\1\u0153\54\0\1\u0154\23\0\1\u0155\15\0\1\u0156\25\0"+
    "\1\u0157\50\0\1\u0158\52\0\1\u0159\37\0\1\u015a\43\0"+
    "\1\u015b\46\0\1\u015c\40\0\1\u015d\53\0\1\u015e\34\0"+
    "\1\u015f\34\0\1\u0160\61\0\1\u0161\32\0\1\u0162\42\0"+
    "\1\u0163\54\0\1\u0164\37\0\1\u0165\50\0\1\u0166\34\0"+
    "\1\u0167\55\0\1\u0168\21\0\1\u0169\62\0\1\u016a\42\0"+
    "\1\u016b\44\0\1\u016c\44\0\1\u016d\34\0\1\u016e\32\0"+
    "\1\u016f\61\0\1\u0170\32\0\1\u0171\35\0\1\u0172\63\0"+
    "\1\u0173\32\0\1\u0174\51\0\1\u0175\35\0\1\u0176\37\0"+
    "\1\u0177\46\0\1\u0178\35\0\1\u0179\54\0\1\u017a\64\0"+
    "\1\u017b\27\0\1\u017c\13\0\1\u017d\23\0\1\u017e\63\0"+
    "\1\u017f\44\0\1\u0180\24\0\1\u0181\30\0\1\u0182\54\0"+
    "\1\u0183\3\0\1\u0184\57\0\1\u0185\26\0\1\u0186\27\0"+
    "\1\u0187\57\0\1\u0188\31\0\1\u0189\61\0\1\u018a\33\0"+
    "\1\u018b\45\0\1\u018c\62\0\1\u018d\20\0\1\u018e\45\0"+
    "\1\u018f\52\0\1\u0190\34\0\1\u0191\41\0\1\u0192\66\0"+
    "\1\u0193\25\0\1\u0194\40\0\1\u0195\64\0\1\u0196\22\0"+
    "\1\u0197\44\0\1\u0198\40\0\1\u0199\43\0\1\u019a\66\0"+
    "\1\u019b\27\0\1\u019c\34\0\1\u019d\66\0\1\u019e\13\0"+
    "\1\u019f\47\0\1\u01a0\55\0\1\u01a1\55\0\1\u01a2\21\0"+
    "\1\u01a3\65\0\1\u01a4\13\0\1\u01a5\50\0\1\u01a6\42\0"+
    "\1\u01a7\43\0\1\u01a8\53\0\1\u01a9\13\0\1\u01aa\23\0"+
    "\1\u01ab\3\0\1\u01ac\37\0\1\u01ad\37\0\1\u01ae\36\0"+
    "\1\u01af\10\0\1\u01b0\17\0\1\u01b1\31\0\1\u01b2\11\0"+
    "\1\u01b3\22\0\1\u01b4\54\0\1\u01b5\42\0\1\u01b6\44\0"+
    "\1\u01b7\44\0\1\u01b8\31\0\1\u01b9\53\0\1\u01ba\55\0"+
    "\1\u01bb\11\0\1\u01bc\45\0\1\u01bd\55\0\1\u01be\36\0"+
    "\1\u01bf\46\0\1\u01c0\40\0\1\u01c1\53\0\1\u01c2\34\0"+
    "\1\u01c3\52\0\1\u01c4\31\0\1\u01c5\50\0\1\u01c6\50\0"+
    "\1\u01c7\34\0\1\u01c8\52\0\1\u01c9\44\0\1\u01ca\25\0"+
    "\1\u01cb\51\0\1\u01cc\34\0\1\u01cd\50\0\1\u01ce\47\0"+
    "\1\u01cf\41\0\1\u01d0\40\0\1\u01d1\43\0\1\u01d2\53\0"+
    "\1\u01d3\26\0\1\u01d4\50\0\1\u01d5\56\0\1\u01d6\41\0"+
    "\1\u01d7\35\0\1\u01d8\40\0\1\u01d9\47\0\1\u01da\32\0"+
    "\1\u01db\52\0\1\u01dc\34\0\1\u01dd\44\0\1\u01de\62\0"+
    "\1\u01df\36\0\1\u01e0\31\0\1\u01e1\13\0\1\u01e2\1\u01e3"+
    "\45\0\1\u01e4\42\0\1\u01e5\35\0\1\u01e6\17\0\1\u01e7"+
    "\20\0\1\u01e8\66\0\1\u01e9\43\0\1\u01ea\43\0\1\u01eb"+
    "\25\0\1\u01ec\41\0\1\u01ed\44\0\1\u01ee\44\0\1\u01ef"+
    "\31\0\1\u01f0\57\0\1\u01f1\43\0\1\u01f2\40\0\1\u01f3"+
    "\62\0\1\u01f4\43\0\1\u01f5\17\0\1\u01f6\67\0\1\u01f7"+
    "\31\0\1\u01f8\55\0\1\u01f9\17\0\1\u01fa\37\0\1\u01fb"+
    "\54\0\1\u01fc\62\0\1\u01fd\26\0\1\u01fe\30\0\1\u01ff"+
    "\57\0\1\u0200\43\0\1\u0201\36\0\1\u0202\53\0\1\u0203"+
    "\54\0\1\u0204\20\0\1\u0205\46\0\1\u0206\52\0\1\u0207"+
    "\23\0\1\u0208\74\0\1\u0209\20\0\1\u020a\52\0\1\u020b"+
    "\34\0\1\u020c\66\0\1\u020d\43\0\1\u020e\16\0\1\u020f"+
    "\47\0\1\u0210\41\0\1\u0211\42\0\1\u0212\50\0\1\u0213"+
    "\41\0\1\u0214\64\0\1\u0215\25\0\1\u0216\61\0\1\u0217"+
    "\22\0\1\u0218\64\0\1\u0219\25\0\1\u021a\30\0\1\u021b"+
    "\53\0\1\u021c\52\0\1\u021d\44\0\1\u021e\33\0\1\u021f"+
    "\41\0\1\u0220\45\0\1\u0221\44\0\1\u0222\44\0\1\u0223"+
    "\40\0\1\u0224\41\0\1\u0225\56\0\1\u0226\10\0\1\u0227"+
    "\12\0\1\u0228\53\0\1\u0229\40\0\1\u022a\67\0\1\u022b"+
    "\31\0\1\u022c\35\0\1\u022d\44\0\1\u022e\43\0\1\u022f"+
    "\41\0\1\u0230\40\0\1\u0231\52\0\1\u0232\35\0\1\u0233"+
    "\66\0\1\u0234\44\0\1\u0235\33\0\1\u0236\21\0\1\u0237"+
    "\50\0\1\u0238\53\0\1\u0239\57\0\1\u023a\22\0\1\u023b"+
    "\50\0\1\u023c\41\0\1\u023d\61\0\1\u023e\44\0\1\u023f"+
    "\6\0\1\u0240\67\0\1\u0241\11\0\1\u0242\41\0\1\u0243"+
    "\31\0\1\u0244\34\0\1\u0245\43\0\1\u0246\35\0\1\u0247"+
    "\55\0\1\u0248\51\0\1\u0249\31\0\1\u024a\64\0\1\u024b"+
    "\50\0\1\u024c\15\0\1\u024d\64\0\1\u024e\23\0\1\u024f"+
    "\63\0\1\u0250\17\0\1\u0251\67\0\1\u0252\24\0\1\u0253"+
    "\50\0\1\u0254\37\0\1\u0255\36\0\1\u0256\36\0\1\u0257"+
    "\46\0\1\u0258\51\0\1\u0259\44\0\1\u025a\41\0\1\u025b"+
    "\63\0\1\u025c\43\0\1\u025d\43\0\1\u025e\43\0\1\u025f"+
    "\25\0\1\u0260\41\0\1\u0261\44\0\1\u0262\40\0\1\u0263"+
    "\41\0\1\u0264\46\0\1\u0265\43\0\1\u0266\33\0\1\u0267"+
    "\61\0\1\u0268\32\0\1\u0269\67\0\1\u026a\26\0\1\u026b"+
    "\60\0\1\u026c\43\0\1\u026d\43\0\1\u026e\12\0\1\u026f"+
    "\1\u0270\5\0\1\u0271\6\0\1\u0272\56\0\1\u0273\24\0"+
    "\1\u0274\32\0\1\u0275\73\0\1\u0276\22\0\1\u0277\66\0"+
    "\1\u0278\20\0\1\u0279\64\0\1\u027a\13\0\1\u027b\50\0"+
    "\1\u027c\66\0\1\u027d\22\0\1\u027e\53\0\1\u027f\33\0"+
    "\1\u0280\47\0\1\u0281\37\0\1\u0282\64\0\1\u0283\13\0"+
    "\1\u0284\73\0\1\u0285\25\0\1\u0286\44\0\1\u0287\64\0"+
    "\1\u0288\16\0\1\u0289\53\0\1\u028a\45\0\1\u028b\32\0"+
    "\1\u028c\63\0\1\u028d\32\0\1\u028e\24\0\1\u028f\73\0"+
    "\1\u0290\43\0\1\u0291\34\0\1\u0292\52\0\1\u0293\22\0"+
    "\1\u0294\43\0\1\u0295\45\0\1\u0296\42\0\1\u0297\51\0"+
    "\1\u0298\37\0\1\u0299\42\0\1\u029a\51\0\1\u029b\41\0"+
    "\1\u029c\15\0\1\u029d\7\0\1\u029e\43\0\1\u029f\60\0"+
    "\1\u02a0\57\0\1\u02a1\43\0\1\u02a2\43\0\1\u02a3\25\0"+
    "\1\u02a4\41\0\1\u02a5\52\0\1\u02a6\25\0\1\u02a7\62\0"+
    "\1\u02a8\36\0\1\u02a9\30\0\1\u02aa\64\0\1\u02ab\34\0"+
    "\1\u02ac\61\0\1\u02ad\43\0\1\u02ae\26\0\1\u02af\43\0"+
    "\1\u02b0\43\0\1\u02b1\60\0\1\u02b2\24\0\1\u02b3\42\0"+
    "\1\u02b4\32\0\1\u02b5\44\0\1\u02b6\56\0\1\u02b7\61\0"+
    "\1\u02b8\23\0\1\u02b9\41\0\1\u02ba\66\0\1\u02bb\44\0"+
    "\1\u02bc\40\0\1\u02bd\43\0\1\u02be\23\0\1\u02bf\46\0"+
    "\1\u02c0\60\0\1\u02c1\20\0\1\u02c2\57\0\1\u02c3\33\0"+
    "\1\u02c4\62\0\1\u02c5\43\0\1\u02c6\25\0\1\u02c7\43\0"+
    "\1\u02c8\43\0\1\u02c9\35\0\1\u02ca\67\0\1\u02cb\22\0"+
    "\1\u02cc\64\0\1\u02cd\43\0\1\u02ce\17\0\1\u02cf\51\0"+
    "\1\u02d0\40\0\1\u02d1\64\0\1\u02d2\25\0\1\u02d3\35\0"+
    "\1\u02d4\57\0\1\u02d5\43\0\1\u02d6\53\0\1\u02d7\34\0"+
    "\1\u02d8\43\0\1\u02d9\22\0\1\u02da\15\0\1\u02db\11\0"+
    "\1\u02dc\23\0\1\u02dd\63\0\1\u02de\43\0\1\u02df\43\0"+
    "\1\u02e0\34\0\1\u02e1\40\0\1\u02e2\36\0\1\u02e3\62\0"+
    "\1\u02e4\43\0\1\u02e5\43\0\1\u02e6\20\0\1\u02e7\51\0"+
    "\1\u02e8\60\0\1\u02e9\43\0\1\u02ea\26\0\1\u02eb\60\0"+
    "\1\u02ec\17\0\1\u02ed\60\0\1\u02ee\32\0\1\u02ef\64\0"+
    "\1\u02f0\32\0\1\u02f1\34\0\1\u02f2\62\0\1\u02f3\24\0"+
    "\1\u02f4\62\0\1\u02f5\43\0\1\u02f6\5\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  1,  0,  0,  0,  9,  0,  0,  0,  1,  9,  1, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  9,  0,  9,  1,  0,  0,  9,  0,  0, 
     0,  9,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  9,  0, 
     1,  0,  0,  0,  9,  9,  0,  9,  0,  9,  9,  9,  9,  9,  9,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  9,  0,  0,  0,  0,  0,  9,  9,  0,  9,  0,  9,  9, 
     9,  0,  0,  9,  9,  9,  9,  9,  9,  0,  0,  0,  0,  0,  9,  9, 
     0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  9, 
     9,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0, 
     0,  0,  0,  0,  9,  9,  0,  0,  0,  0,  9,  9,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  9,  0,  9,  0, 
     0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0, 
     0,  0,  9,  0,  0,  9,  0,  0,  0,  0,  9,  9,  0,  9,  0,  0, 
     0,  9,  0,  9,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0, 
     9,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  9,  9, 
     0,  0,  0,  0,  0,  0,  9,  1,  9,  0,  9,  9,  9,  0,  9,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  9,  0,  9,  9,  9,  0,  0,  0,  0,  0, 
     0,  0,  0,  9,  9,  0,  9,  0,  9,  0,  0,  0,  9,  0,  0,  9, 
     0,  0,  0,  9,  0,  0,  0,  0,  9,  0,  0,  0,  9,  9,  0,  0, 
     0,  0,  0,  0,  9,  0,  9,  0,  9,  9,  0,  0,  9,  0,  9,  0, 
     0,  0,  9,  0,  9,  0,  9,  0,  0,  0,  9,  0,  0,  0,  0,  0, 
     0,  0,  0,  9,  0,  0,  0,  0,  0,  9,  0,  0,  0,  9,  0,  0, 
     0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  9,  0,  9,  9,  0,  9, 
     0,  9,  9,  0,  0,  0,  0,  0,  0,  0,  0,  9,  9,  9,  9,  9, 
     0,  9,  0,  9,  0,  0,  0,  0,  0,  9,  0,  9,  9,  9,  0,  0, 
     0,  0,  9,  0,  0,  9,  0,  0,  0,  9,  9,  0,  9,  0,  0,  0, 
     0,  9,  9,  9,  9,  0,  0,  0,  9,  0,  0,  9,  9,  0,  0,  9, 
     9,  0,  9,  0,  0,  9,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     9,  9,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  9,  0,  0, 
     0,  9,  9,  9,  0,  0,  0,  0,  0,  0,  0,  0,  9,  9,  0,  0, 
     9,  0,  0,  0,  9,  9,  0,  0,  0,  0,  9,  0,  9,  9,  0,  0, 
     0,  9,  0,  0,  0,  0,  9,  0,  0,  0,  0,  9,  0,  9,  9,  9, 
     0,  0,  0,  9,  9,  9,  0,  0,  9,  9,  0,  9,  0,  0,  0,  0, 
     0,  0,  9,  0,  9,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    StringBuffer string = new StringBuffer();

    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[21456];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 94) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 741: 
          {  return symbol(sym.cellpadding);  }
        case 759: break;
        case 740: 
          {  return symbol(sym.cellspacing);  }
        case 760: break;
        case 739: 
          {  return symbol(sym.marginwidth);  }
        case 761: break;
        case 735: 
          {  return symbol(sym.onmousemove);  }
        case 762: break;
        case 734: 
          {  return symbol(sym.onmousedown);  }
        case 763: break;
        case 733: 
          {  return symbol(sym.onmouseover);  }
        case 764: break;
        case 731: 
          {  return symbol(sym.bordercolor);  }
        case 765: break;
        case 726: 
          {  return symbol(sym.leftmargin);  }
        case 766: break;
        case 721: 
          {  return symbol(sym.onkeypress);  }
        case 767: break;
        case 717: 
          {  return symbol(sym.onmouseout);  }
        case 768: break;
        case 716: 
          {  return symbol(sym.ondblclick);  }
        case 769: break;
        case 714: 
          {  return symbol(sym.background);  }
        case 770: break;
        case 537: 
          {  return symbol(sym.optionOpen);  }
        case 771: break;
        case 540: 
          {  return symbol(sym.smallClose);  }
        case 772: break;
        case 542: 
          {  return symbol(sym.tableClose);  }
        case 773: break;
        case 546: 
          {  return symbol(sym.selectOpen);  }
        case 774: break;
        case 548: 
          {  return symbol(sym.centerOpen);  }
        case 775: break;
        case 607: 
          {  return symbol(sym.optionClose);  }
        case 776: break;
        case 609: 
          {  return symbol(sym.selectClose);  }
        case 777: break;
        case 611: 
          {  return symbol(sym.centerClose);  }
        case 778: break;
        case 709: 
          {  return symbol(sym.topmargin);  }
        case 779: break;
        case 708: 
          {  return symbol(sym.scrolling);  }
        case 780: break;
        case 704: 
          {  return symbol(sym.accesskey);  }
        case 781: break;
        case 701: 
          {  return symbol(sym.onkeydown);  }
        case 782: break;
        case 700: 
          {  return symbol(sym.onmouseup);  }
        case 783: break;
        case 689: 
          {  return symbol(sym.hreflang);  }
        case 784: break;
        case 685: 
          {  return symbol(sym.longdesc);  }
        case 785: break;
        case 454: 
          {  return symbol(sym.htmlClose);  }
        case 786: break;
        case 447: 
          {  return symbol(sym.fontClose);  }
        case 787: break;
        case 446: 
          {  return symbol(sym.formClose);  }
        case 788: break;
        case 444: 
          {  return symbol(sym.bodyClose);  }
        case 789: break;
        case 357: 
          {  return symbol(sym.htmlOpen);  }
        case 790: break;
        case 347: 
          {  return symbol(sym.fontOpen);  }
        case 791: break;
        case 346: 
          {  return symbol(sym.formOpen);  }
        case 792: break;
        case 341: 
          {  return symbol(sym.supClose);  }
        case 793: break;
        case 340: 
          {  return symbol(sym.subClose);  }
        case 794: break;
        case 331: 
          {  return symbol(sym.bodyOpen);  }
        case 795: break;
        case 455: 
          {  return symbol(sym.frameOpen);  }
        case 796: break;
        case 456: 
          {  return symbol(sym.smallOpen);  }
        case 797: break;
        case 459: 
          {  return symbol(sym.tableOpen);  }
        case 798: break;
        case 634: 
          {  return symbol(sym.disabled);  }
        case 799: break;
        case 641: 
          {  return symbol(sym.multiple);  }
        case 800: break;
        case 643: 
          {  return symbol(sym.selected);  }
        case 801: break;
        case 648: 
          {  return symbol(sym.noresize);  }
        case 802: break;
        case 651: 
          {  return symbol(sym.controls);  }
        case 803: break;
        case 672: 
          {  return symbol(sym.onsubmit);  }
        case 804: break;
        case 673: 
          {  return symbol(sym.onunload);  }
        case 805: break;
        case 674: 
          {  return symbol(sym.onchange);  }
        case 806: break;
        case 684: 
          {  return symbol(sym.tabindex);  }
        case 807: break;
        case 432: 
          {  return symbol(sym.chr);  }
        case 808: break;
        case 285: 
          {  return symbol(sym.src);  }
        case 809: break;
        case 275: 
          {  return symbol(sym.alt);  }
        case 810: break;
        case 272: 
          {  return symbol(sym.rev);  }
        case 811: break;
        case 271: 
          {  return symbol(sym.rel);  }
        case 812: break;
        case 266: 
          {  return symbol(sym.dir);  }
        case 813: break;
        case 244: 
          {  return symbol(sym.img);  }
        case 814: break;
        case 87: 
          {  return symbol(sym.br);  }
        case 815: break;
        case 119: 
          {  return symbol(sym.hr);  }
        case 816: break;
        case 181: 
          {  return symbol(sym.id);  }
        case 817: break;
        case 524: 
          {  return symbol(sym.cls);  }
        case 818: break;
        case 747: 
          {  return symbol(sym.marginheight);  }
        case 819: break;
        case 745: 
          {  return symbol(sym.framespacing);  }
        case 820: break;
        case 744: 
          {  return symbol(sym.bgproperties);  }
        case 821: break;
        case 691: 
          {  return symbol(sym.noframesClose);  }
        case 822: break;
        case 690: 
          {  return symbol(sym.framesetClose);  }
        case 823: break;
        case 661: 
          {  return symbol(sym.framesetOpen);  }
        case 824: break;
        case 662: 
          {  return symbol(sym.noframesOpen);  }
        case 825: break;
        case 434: 
          {  return symbol(sym.href);  }
        case 826: break;
        case 425: 
          {  return symbol(sym.cols);  }
        case 827: break;
        case 419: 
          {  return symbol(sym.link);  }
        case 828: break;
        case 417: 
          {  return symbol(sym.lang);  }
        case 829: break;
        case 413: 
          {  return symbol(sym.loop);  }
        case 830: break;
        case 411: 
          {  return symbol(sym.ismap);  }
        case 831: break;
        case 410: 
          {  return symbol(sym.name);  }
        case 832: break;
        case 405: 
          {  return symbol(sym.text);  }
        case 833: break;
        case 402: 
          {  return symbol(sym.type);  }
        case 834: break;
        case 396: 
          {  return symbol(sym.size);  }
        case 835: break;
        case 388: 
          {  return symbol(sym.axis);  }
        case 836: break;
        case 382: 
          {  return symbol(sym.abbr);  }
        case 837: break;
        case 380: 
          {  return symbol(sym.rows);  }
        case 838: break;
        case 378: 
          {  return symbol(sym.face);  }
        case 839: break;
        case 21: 
          {  return symbol(sym.bOpen);  }
        case 840: break;
        case 25: 
          {  return symbol(sym.aOpen);  }
        case 841: break;
        case 29: 
          {  return symbol(sym.iOpen);  }
        case 842: break;
        case 30: 
          {  return symbol(sym.pOpen);  }
        case 843: break;
        case 31: 
          {  return symbol(sym.uOpen);  }
        case 844: break;
        case 458: 
          {  return symbol(sym.tbody);  }
        case 845: break;
        case 462: 
          {  return symbol(sym.input);  }
        case 846: break;
        case 486: 
          {  return symbol(sym.frame);  }
        case 847: break;
        case 488: 
          {  return symbol(sym.rules);  }
        case 848: break;
        case 489: 
          {  return symbol(sym.alink);  }
        case 849: break;
        case 490: 
          {  return symbol(sym.align);  }
        case 850: break;
        case 499: 
          {  return symbol(sym.style);  }
        case 851: break;
        case 500: 
          {  return symbol(sym.start);  }
        case 852: break;
        case 502: 
          {  return symbol(sym.scope);  }
        case 853: break;
        case 504: 
          {  return symbol(sym.shape);  }
        case 854: break;
        case 508: 
          {  return symbol(sym.title);  }
        case 855: break;
        case 515: 
          {  return symbol(sym.label);  }
        case 856: break;
        case 520: 
          {  return symbol(sym.color);  }
        case 857: break;
        case 525: 
          {  return symbol(sym.clear);  }
        case 858: break;
        case 532: 
          {  return symbol(sym.width);  }
        case 859: break;
        case 534: 
          {  return symbol(sym.value);  }
        case 860: break;
        case 536: 
          {  return symbol(sym.vlink);  }
        case 861: break;
        case 757: 
          {  return symbol(sym.bordercolorlight);  }
        case 862: break;
        case 756: 
          {  return symbol(sym.acceptcharlist);  }
        case 863: break;
        case 754: 
          {  return symbol(sym.bordercolordark);  }
        case 864: break;
        case 239: 
          {  return symbol(sym.supOpen);  }
        case 865: break;
        case 238: 
          {  return symbol(sym.subOpen);  }
        case 866: break;
        case 232: 
          {  return symbol(sym.h6Close);  }
        case 867: break;
        case 231: 
          {  return symbol(sym.h5Close);  }
        case 868: break;
        case 230: 
          {  return symbol(sym.h4Close);  }
        case 869: break;
        case 117: 
          {  return symbol(sym.liOpen);  }
        case 870: break;
        case 116: 
          {  return symbol(sym.ulOpen);  }
        case 871: break;
        case 112: 
          {  return symbol(sym.thOpen);  }
        case 872: break;
        case 110: 
          {  return symbol(sym.trOpen);  }
        case 873: break;
        case 109: 
          {  return symbol(sym.tdOpen);  }
        case 874: break;
        case 99: 
          {  return symbol(sym.uClose);  }
        case 875: break;
        case 97: 
          {  return symbol(sym.iClose);  }
        case 876: break;
        case 93: 
          {  return symbol(sym.aClose);  }
        case 877: break;
        case 90: 
          {  return symbol(sym.bClose);  }
        case 878: break;
        case 2: 
          {  return symbol(sym.endTag);  }
        case 879: break;
        case 89: 
          {  return symbol(sym.olOpen);  }
        case 880: break;
        case 121: 
          {  return symbol(sym.h1Open);  }
        case 881: break;
        case 122: 
          {  return symbol(sym.h2Open);  }
        case 882: break;
        case 123: 
          {  return symbol(sym.h3Open);  }
        case 883: break;
        case 124: 
          {  return symbol(sym.h4Open);  }
        case 884: break;
        case 125: 
          {  return symbol(sym.h5Open);  }
        case 885: break;
        case 126: 
          {  return symbol(sym.h6Open);  }
        case 886: break;
        case 211: 
          {  return symbol(sym.olClose);  }
        case 887: break;
        case 217: 
          {  return symbol(sym.tdClose);  }
        case 888: break;
        case 218: 
          {  return symbol(sym.trClose);  }
        case 889: break;
        case 220: 
          {  return symbol(sym.thClose);  }
        case 890: break;
        case 222: 
          {  return symbol(sym.pClose);  }
        case 891: break;
        case 223: 
          {  return symbol(sym.ulClose);  }
        case 892: break;
        case 224: 
          {  return symbol(sym.liClose);  }
        case 893: break;
        case 227: 
          {  return symbol(sym.h1Close);  }
        case 894: break;
        case 228: 
          {  return symbol(sym.h2Close);  }
        case 895: break;
        case 229: 
          {  return symbol(sym.h3Close);  }
        case 896: break;
        case 460: 
          {  return symbol(sym.thread);  }
        case 897: break;
        case 511: 
          {  return symbol(sym.nowrap);  }
        case 898: break;
        case 550: 
          {  return symbol(sym.border);  }
        case 899: break;
        case 554: 
          {  return symbol(sym.onblur);  }
        case 900: break;
        case 563: 
          {  return symbol(sym.onload);  }
        case 901: break;
        case 569: 
          {  return symbol(sym.dynsrc);  }
        case 902: break;
        case 573: 
          {  return symbol(sym.action);  }
        case 903: break;
        case 578: 
          {  return symbol(sym.method);  }
        case 904: break;
        case 586: 
          {  return symbol(sym.target);  }
        case 905: break;
        case 588: 
          {  return symbol(sym.noshade);  }
        case 906: break;
        case 589: 
          {  return symbol(sym.usemap);  }
        case 907: break;
        case 591: 
          {  return symbol(sym.lowsrc);  }
        case 908: break;
        case 593: 
          {  return symbol(sym.coords);  }
        case 909: break;
        case 594: 
          {  return symbol(sym.compact);  }
        case 910: break;
        case 603: 
          {  return symbol(sym.height);  }
        case 911: break;
        case 604: 
          {  return symbol(sym.hspace);  }
        case 912: break;
        case 605: 
          {  return symbol(sym.valign);  }
        case 913: break;
        case 606: 
          {  return symbol(sym.vspace);  }
        case 914: break;
        case 617: 
          {  return symbol(sym.bgcolor);  }
        case 915: break;
        case 619: 
          {  return symbol(sym.onfocus);  }
        case 916: break;
        case 620: 
          {  return symbol(sym.onreset);  }
        case 917: break;
        case 621: 
          {  return symbol(sym.onabort);  }
        case 918: break;
        case 626: 
          {  return symbol(sym.onerror);  }
        case 919: break;
        case 629: 
          {  return symbol(sym.onclick);  }
        case 920: break;
        case 633: 
          {  return symbol(sym.onkeyup);  }
        case 921: break;
        case 636: 
          {  return symbol(sym.rowspan);  }
        case 922: break;
        case 642: 
          {  return symbol(sym.enctype);  }
        case 923: break;
        case 644: 
          {  return symbol(sym.summary);  }
        case 924: break;
        case 652: 
          {  return symbol(sym.colspan);  }
        case 925: break;
        case 655: 
          {  return symbol(sym.charoff);  }
        case 926: break;
        case 656: 
          {  return symbol(sym.charset);  }
        case 927: break;
        case 658: 
          {  return symbol(sym.headers);  }
        case 928: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
